-- As databases get large, we need indexes
-- what an index is, you can think of an index like an index in a book,
-- it is an easy way that if I'm looking for something I can quickly reference something else.
-- And so what you can do is SQL is add an index to a particular column.
-- To say that if I'm going to be referencing flights by their origin a lot, it might be helpful if I had an index
-- of the origin of all of my flights.
